### ISSUE TITLE
CPU usage on windows

### ISSUE THREAD

**Issue by HDPLocust** [SEVA77/circuitjs1#1] opened 2019-01-09 11:42 UTC
![image](https://user-images.githubusercontent.com/13125395/50897238-943a4f80-141c-11e9-942e-12a9c19644fa.png)
Please add a pause or sleep at the end of the calc cycles! 👍

**Comment by CEBA77** [comment] 2019-01-12 21:56
If I understood correctly, the problem is that the calculations continue even when the Start/Stop button is pressed and the simulation is stopped.

In the program code there are a lot of cycles with such calculations. So far, I’m just assuming how this problem can be solved, but this may have some consequences... Perhaps it will be even more difficult than I think. I can't handle this alone.

At the moment I don’t have time to do it. I can contact the other developers (@sharpie7 and @pfalstad) of the program and explain this problem to them, since this problem also applies to the web application as a whole.

**Comment by CEBA77** [comment] 2019-02-07 01:19
@pfalstad I would be uncomfortable to add workload for you, but I have very little practice writing applications in Java. I can spoil the code if I will try to solve the problem. The simplest in this situation is to write in cycles
```java
   if (simRunning == false) {
   break; 
   };
```
but not all cycles are related to simulation...
Will you solve this problem?

**Comment by pfalstad** [comment] 2019-02-08 01:43
I already fixed this, and thought I uploaded it to github, but I see I haven't.  I'll try to do that soon.

It's not hard but it's a little more complicated than that, because you want to stop calling updateCircuit() at all if the sim is not running.

**Comment by pfalstad** [comment] 2019-03-10 02:53
ok this is fixed in 10ad78fabc75a2cfb011fa6c3b6d27ee8a92a358

**Comment by CEBA77** [comment] 2019-03-16 16:36
@pfalstad "Scheduler"? Not bad. I didn't know about it...
It is wonderful! Thank you very much!

**Closed** 2020-05-14 14:53 UTC
